Pineapple-Studios/tears-of-fire

Assets/Prefabs/Engines/Drop.prefab, Assets/Prefabs/Engines/Leak.prefab, Assets/Prefabs/Engines/Leak.prefab.meta, Assets/Prefabs/Items.meta, Assets/Prefabs/Items/ActiveComponentItem.prefab, Assets/Prefabs/Items/ActiveComponentItem.prefab.meta, Assets/Prefabs/Items/LifeItem.prefab, Assets/Prefabs/Items/LifeItem.prefab.meta, Assets/_Scenes/Levels/Tutorial.unity, Assets/_Scenes/Playground/EnginesRoom.unity, Assets/_Scripts/Engines/Drop.cs, Assets/_Scripts/Engines/HiddenPath.cs, Assets/_Scripts/Engines/HiddenPath.cs.meta, Assets/_Scripts/Engines/Leak.cs, Assets/_Scripts/Items.meta, Assets/_Scripts/Items/ActiveComponentItem.cs, Assets/_Scripts/Items/ActiveComponentItem.cs.meta, Assets/_Scripts/Items/LifeItem.cs, Assets/_Scripts/Items/LifeItem.cs.meta, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/Utils/MovimentBetweenPointsElement.cs, ProjectSettings/TagManager.asset
- Create Leak engine, on Prefab folder you will have the engines there;
- Create Hidden Path engine;
- Create Heal Item;
- Create dash activation Item;
=> [TOF-62]: Create game engines

Assets/Prefabs/Engines/Checkpoint.prefab, Assets/Prefabs/Engines/Checkpoint.prefab.meta, Assets/Prefabs/Player/Player.prefab, Assets/_Scenes/Playground/EnginesRoom.unity, Assets/_Scripts/Camera/CameraFollowObject.cs, Assets/_Scripts/Engines/Checkpoint.cs, Assets/_Scripts/Engines/Checkpoint.cs.meta, Assets/_Scripts/Managers/LevelDataManager.cs, Assets/_Scripts/Managers/LevelDataManager.cs.meta, Assets/_Scripts/Managers/ScenarioColorManager.cs, Assets/_Scripts/ScriptableObjects.meta, Assets/_Scripts/ScriptableObjects/LevelDataScriptableObject.cs, Assets/_Scripts/ScriptableObjects/LevelDataScriptableObject.cs.meta, Assets/_Storages.meta, Assets/_Storages/LevelTutorialData.asset, Assets/_Storages/LevelTutorialData.asset.meta
- Add leak
- Add drop
- Add checkpoint
- Add Hidden Path
- Add heal item
- Add enable engine from item
N/A
=> [TOF-62]: Feat - Add engines to main project

ProjectSettings/BurstAotSettings_StandaloneWindows.json, ProjectSettings/CommonBurstAotSettings.json, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/ProjectSettings.asset
Adicionado mais inimigos na cena, regulado os rayscast de cada um.
=> Add inimigos tutorial

Assets/Prefabs/Engines/FovChanger.prefab, Assets/Prefabs/Engines/FovChanger.prefab.meta, Assets/_Scenes/Playground/EnginesRoom.unity, Assets/_Scripts/Engines/FOVChanger.cs, Assets/_Scripts/Engines/FOVChanger.cs.meta, Assets/_Scripts/Managers/LevelDataManager.cs
Create a component which handle the Fov of current camera;
- Set the main virtual camera to the 'LevelDataManager' 
- Use the prefab 'FovChanger' on prefab/engines folder
- Set the 'PlayerLayer' on the engines of the component
- Setup the fov points on the Engines component of ´FovChanger` prefab;
=> Add fov component

Assets/Prefabs/Engines/BreakableBlock.prefab, Assets/Prefabs/Engines/BreakableBlock.prefab.meta, Assets/Prefabs/HUD/btn_goTo.prefab, Assets/Prefabs/HUD/btn_goTo.prefab.meta, Assets/Prefabs/Player/Player.prefab, Assets/_Scenes/Playground/EnginesRoom.unity, Assets/_Scripts/Engines/BreakableBlock.cs, Assets/_Scripts/Engines/BreakableBlock.cs.meta, Assets/_Scripts/Managers/FeedbackAndDebugManager.cs, Assets/_Scripts/Managers/FeedbackAndDebugManager.cs.meta, Assets/_Scripts/Player/PlayerCombat.cs, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/ScriptableObjects/FeedbackAndDebugScriptableObject.cs, Assets/_Scripts/ScriptableObjects/FeedbackAndDebugScriptableObject.cs.meta, Assets/_Scripts/ScriptableObjects/LevelDataScriptableObject.cs, Assets/_Scripts/UI/GoTo.cs, Assets/_Scripts/UI/GoTo.cs.meta, Assets/_Storages/GameDebugTool.asset, Assets/_Storages/GameDebugTool.asset.meta, ProjectSettings/TagManager.asset
- Add debug tools
- Add breakable blocks
=> [TOF-145]: Add debug tools feature

Assets/Prefabs/Enemies/bat_bullet.prefab, Assets/Prefabs/Enemies/jumper.prefab, Assets/Prefabs/Engines/BreakableBlock.prefab, Assets/Prefabs/Engines/Magnetic.prefab, Assets/Prefabs/Player/Player.prefab, Assets/_Scenes/Playground/EnemyRoom.unity, Assets/_Scripts/Enemies/BatBullet.cs, Assets/_Scripts/Enemies/Enemy.cs, Assets/_Scripts/Enemies/Jumper.cs, Assets/_Scripts/Engines/BreakableBlock.cs, Assets/_Scripts/Engines/MagneticPuzzle.cs, Assets/_Scripts/Player/PlayerController.cs, Assets/_Scripts/Player/PlayerDash.cs, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/Utils/TrackedMoviment.cs
- Fix Bug's presents on ticket https://pinealpple-studios.atlassian.net/browse/TOF-138
- Destroy bat bullets when hit walls
- Enable right direction to brackable wall
- Fix magnetic puzzle
- Fix Knockback
- Fix "dead-floating" bug's dash related
- Fix spider behaviours;
N/A
=> [TOF-138]: Correção de Bugs

Assets/Inputs/InputActions.cs, Assets/Inputs/InputActions.inputactions, Assets/_Scenes/Levels/Mid-Game-Data.asset, Assets/_Scenes/Levels/Mid-Game-Data.asset.meta, Assets/_Scenes/Levels/Mid-Game.unity.meta, ProjectSettings/EditorBuildSettings.asset
*  Nova Cena Mid-Game
*  Esqueleto do Level Design completo
*  Todos os cameras bound add
=> Level Design 2 Fase

Assets/_Scenes/Playground/PauseMenu.unity, Assets/_Scenes/UI/MainMenu.unity, Assets/_Scripts/UI/PauseManager.cs
Sliders from canvas "cv_Audio" was fixed
Now, cursor are invisible and visible just when you pause.
=> Fix/Pause and Fix/Sliders

Assets/Animations/Enemies/dashBoss/ac_dashBoss.controller, Assets/Animations/Enemies/dashBoss/dashing.anim, Assets/Animations/Enemies/dashBoss/prep_dash.anim, Assets/Animations/Player/ac_Svart.controller, Assets/_Scenes/Playground/BossRoom.unity, Assets/_Scripts/Enemies/DashBoss.meta, Assets/_Scripts/Enemies/DashBoss/AnchorPoint.cs, Assets/_Scripts/Enemies/DashBoss/AnchorPoint.cs.meta, Assets/_Scripts/Enemies/DashBoss/BossMoviment.cs, Assets/_Scripts/Enemies/DashBoss/BossMoviment.cs.meta, Assets/_Scripts/Enemies/DashBoss/BossProps.cs, Assets/_Scripts/Enemies/DashBoss/BossProps.cs.meta, Assets/_Scripts/Enemies/DashBoss/PlayerTrack.cs, Assets/_Scripts/Enemies/DashBoss/PlayerTrack.cs.meta
- Implement boss props
- Implement boss moviment
- Defining tears
- Defining UI to help implementation
N/A
=> [TOF-68]: Finish Boss moviment

Assets/Animations/Player/ac_Svart.controller, Assets/Animations/Player/clip_attackATransition.anim, Assets/Prefabs/Engines/Checkpoint.prefab, Assets/Prefabs/Player/Player.prefab, Assets/_Scripts/Enemies/Enemy.cs, Assets/_Scripts/Engines/MagneticPuzzle.cs, Assets/_Scripts/Managers/LevelDataManager.cs, Assets/_Scripts/Player/DeathToRespawnBehaviour.cs, Assets/_Scripts/Player/DeathToRespawnBehaviour.cs.meta, Assets/_Scripts/Player/EnableControllerAfterRespawnBehaviour.cs, Assets/_Scripts/Player/EnableControllerAfterRespawnBehaviour.cs.meta, Assets/_Scripts/Player/PlayerAnimationController.cs, Assets/_Scripts/Player/PlayerController.cs
- Add dead and respawn anim to svart
N/A
=> FIX: Add dead an respawn anim to svart

Assets/JumperAnimationHandler.cs, Assets/JumperAnimationHandler.cs.meta, Assets/JumperDefiningDirection.cs, Assets/JumperDefiningDirection.cs.meta, Assets/JumperV2.cs, Assets/JumperV2.cs.meta, Assets/Prefabs/Enemies/jumper_v2.prefab, Assets/Prefabs/Enemies/jumper_v2.prefab.meta, Assets/Prefabs/Player/Player.prefab, Assets/Prefabs/Scenario/TransitionSection.prefab, Assets/Prefabs/Scenario/TransitionSection.prefab.meta, Assets/_Scenes/Playground/EnemyRoom.unity, Assets/_Scripts/Enemies/Enemy.cs, Assets/_Scripts/Engines/NextLevelDoor.cs, Assets/_Scripts/Engines/NextLevelDoor.cs.meta, Assets/_Scripts/Player/PlayerController.cs, ProjectSettings/EditorBuildSettings.asset
- Solve bugs
- New spider version
- Exit level doors
=> Add new features to LT

Assets/Prefabs/Music.meta, Assets/Prefabs/Music/as_Music.prefab, Assets/Prefabs/Music/as_Music.prefab.meta, Assets/Prefabs/Music/aud_SoundManager.prefab, Assets/Prefabs/Music/aud_SoundManager.prefab.meta, Assets/Prefabs/Player/Player.prefab, Assets/Prefabs/VFX/Fire.prefab, Assets/Sounds/Tutorial.meta, Assets/Sounds/Tutorial/OST_Tutorial_Start.wav.meta, Assets/Sounds/Tutorial/OST_Tutorial_loop.wav.meta, Assets/_Scenes/UI/MainMenu.unity, Assets/_Scripts/Audio/MusicTutorial.cs, Assets/_Scripts/Audio/MusicTutorial.cs.meta, Assets/_Scripts/Player/PlayerDash.cs, Assets/_Scripts/UI/TypeMachine.cs, Assets/_Scripts/Utils/AffectPlayerMovement.cs
=> MusicTutorial

ProjectSettings/ProjectSettings.asset
Refinado mov svart
Refinado mov magnetismo
Refinado bugs com a camera
N/A
=> Refino svart/engines

Assets/Animations/Checkpoint.meta, Assets/Animations/Checkpoint/ac_Checkpoint.controller, Assets/Animations/Checkpoint/ac_Checkpoint.controller.meta, Assets/Animations/Checkpoint/clip_idle.anim, Assets/Animations/Checkpoint/clip_idle.anim.meta, Assets/Animations/Checkpoint/clip_on.anim, Assets/Animations/Checkpoint/clip_on.anim.meta, Assets/Prefabs/Enemies/jumper_v2.prefab, Assets/Prefabs/Scenario/Checkpoint.prefab, Assets/Prefabs/Scenario/Checkpoint.prefab.meta, Assets/_Scenes/Levels/TutorialData.asset, Assets/_Scenes/Playground/EnemyRoom.unity, Assets/_Scripts/Enemies/Jumper.cs, Assets/_Scripts/Enemies/JumperAnimationHandler.cs, Assets/_Scripts/Enemies/JumperV2.cs, Assets/_Scripts/Engines/Checkpoint.cs, Assets/_Scripts/Engines/MagneticPuzzle.cs, Assets/_Scripts/Managers/LevelDataManager.cs, Assets/_Scripts/Player/PlayerController.cs, ProjectSettings/ProjectSettings.asset
=> [FIX]: Fix jump and rules

Assets/Animations/UI/clip_first_load.anim, Assets/Ink/_Scripts/DialogueHandler.cs, Assets/Ink/_Scripts/DialogueManager.cs, Assets/Inputs/InputActions.cs, Assets/Inputs/InputActions.inputactions, Assets/_Scenes/Playground/NarrativeRoom.unity, Assets/_Scripts/Enemies/Enemy.cs, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/Playground/TucanoRexProps.cs, Assets/_Scripts/UI/SetupInputActions.cs, ProjectSettings/EditorBuildSettings.asset
https://pinealpple-studios.atlassian.net/browse/TOF-246
https://pinealpple-studios.atlassian.net/browse/TOF-264
Feedback háptico (Rumble) finalizado, e adicionado joysticks, mais alguns bugs concertados.
Foi instanciado na função TakeDamage(), a função de RumblePulse. Quanto ao joystick, apenas foi adicionado ao mapa do Input Actions, devido as funções já estarem nos scripts desde o semestre passado.
N/A
N/A
=> February finished

Assets/Inputs/InputActions.cs, Assets/Inputs/InputActions.inputactions, Assets/_Scenes/Playground/BossRoom.unity, Assets/_Scripts/Player/PlayerAnimationController.cs, Assets/_Scripts/Player/PlayerCombat.cs, Assets/_Scripts/Player/PlayerController.cs, Assets/_Scripts/Player/PlayerInputHandler.cs, Assets/_Scripts/Player/PlayerInputHandler.cs.meta, Assets/_Scripts/Player/PlayerPositioningAttack.cs, Assets/_Scripts/Player/PlayerPuzzleHandler.cs, ProjectSettings/ProjectSettings.asset
=> NO-TICKET: Fix inputs to use the same handler

Assets/Ink/_Scripts/DialogueHandler.cs, Assets/Ink/_Scripts/DialogueManager.cs
https://pinealpple-studios.atlassian.net/browse/TOF-292
Implementação dos NPC's finalizada, aberta apenas para alterações de arte.
Na cena "Tutorial" é possível interagir com todos os NPC's e seus diálogos corretamente.
Interagi com todos os NPC's no ciclo inteiro do jogo.
N/A
=> Finished NPC Dialogues

Assets/Animations/Playground/ac_TucanoRex.controller, Assets/Prefabs/Debug/FeedbackAndDebugManager.prefab, Assets/Prefabs/Player/Player.prefab, Assets/Prefabs/Playground/Bossfight.prefab, Assets/_Scenes/Levels/TutorialData.asset, Assets/_Scripts/Engines/DoorLockedFeedbackHandler.cs, Assets/_Scripts/Engines/DoorLockedFeedbackHandler.cs.meta, Assets/_Scripts/Engines/NextLevelDoor.cs, Assets/_Scripts/Managers/FeedbackAndDebugManager.cs, Assets/_Scripts/Managers/LevelDataManager.cs, Assets/_Scripts/Player/PlayerItems.cs, Assets/_Scripts/Player/PlayerItems.cs.meta, Assets/_Scripts/Playground/TucanoRex.cs, Assets/_Scripts/Playground/TucanoRexProps.cs, Assets/_Scripts/ScriptableObjects/FeedbackAndDebugScriptableObject.cs, Assets/_Scripts/ScriptableObjects/LevelDataScriptableObject.cs, Assets/_Storages/GameDebugTool.asset
https://pinealpple-studios.atlassian.net/browse/TOF-370
https://pinealpple-studios.atlassian.net/browse/TOF-351
https://pinealpple-studios.atlassian.net/browse/TOF-369
https://pinealpple-studios.atlassian.net/browse/TOF-382
- Build full expirience não estava completa;
- O boss não estava reiniciando
- A porta desejada não existia
- Svart perdia os inputs mas a gravidade ao sair do estágio permanecia em 10;
- Adicionado mecânica da chave-porta;
- Ataques no mouse são respeitados pelos inputs do novo input system;
- Ao sair do level a gravidade no svart é 0;
- Boss reinicia após a morte do svart;
- Adicionei a mecânica da chave na ferramenta de debug;
```
Eu como Jogador
Executei a ferramenta de debug para não ter a chave
E ao chegar na sala do Boss
Então o jogador não pode acessar a sala …
```
=> [TOF-370] Tutorial Magnetísmo

Assets/Ink/_Scripts/DialogueHandler.cs, Assets/Ink/_Scripts/DialogueManager.cs, Assets/_Scripts/UI/Btn/BtnGoToScreen.cs
https://pinealpple-studios.atlassian.net/browse/TOF-367
https://pinealpple-studios.atlassian.net/browse/TOF-393
https://pinealpple-studios.atlassian.net/browse/TOF-399
Bugs de diálogos
Nas cutscenes houve um bug, mas quando testei estava normal e para garantir coloquei no script da cena para que o cursor esteja visivel independente. 
Nos diálogos, após terminar com o yke ele ativa a chave para a sala do boss, e outros bugs pontuais.
Ajustei os botões de interação que estavam invisíveis.
full gameplay
n/a
=> Bugs Específicos

ProjectSettings/ScriptableBuildPipeline.json
N/A
Arrumei alguns caminhos e bugs relacionado a posicionamento dos FoV.
Arrumei o posicionamento da porta do boss, que estava fora do lugar.
Apenas reposicionei as coisas e criei alguns FoV Changer novos.
N/A
N/A
=> Ajustes no FoV e alguns erros

Assets/Ink/_Scripts/DialogueHandler.cs, Assets/Ink/_Scripts/DialogueManager.cs
https://pinealpple-studios.atlassian.net/browse/TOF-
N/A
N/A
Full gameplay da build
N/A
=> Build 03-22-24

Assets/Animations/NPC/Oce/clip_idle.anim, Assets/Animations/NPC/Yxo/clip_idle.anim, Assets/Prefabs/NPC/TextBox.prefab, Assets/Video/Cutscene/CutsceneBeforeGame.mp4.meta, Assets/_Scenes/Cutscene/BeforeGame.unity
https://pinealpple-studios.atlassian.net/browse/TOF-375
Animação dos balões de interação
Refinei a caixa de diálogo (Tamanho das fontes e troquei o "Press E to continue" para a tecla E)
Editei a cutscene, de apresentação de mundo, colocando o áudio
N/A
Gameplay ponta a ponta
N/A
=> Animation and Cutscene

.gitignore, Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset, Assets/Prefabs/HUD/cv_HUD.prefab, Assets/Prefabs/Music/as_Music.prefab, Assets/Prefabs/UI/CameraUI.prefab, Assets/_Scenes/UI/MainMenu.unity, Assets/_Scripts/Audio/BtnHoverSound.cs, Assets/_Scripts/Audio/FMOD.meta, Assets/_Scripts/Audio/FMOD/FMODSnapshotCaller.cs, Assets/_Scripts/Audio/FMOD/FMODSnapshotCaller.cs.meta, Assets/_Scripts/Audio/FMOD/FMODVolumeController.cs, Assets/_Scripts/Audio/FMOD/FMODVolumeController.cs.meta, Assets/_Sprites/yke-boss-bossFight.png.meta, ProjectSettings/AudioManager.asset
No ticket
N/A
Add FMOD para o projeto
```
Eu como ...
Executei ...
E ...
Então ...
```
N/A
=> Integrate FMOD to project

Assets/AddressableAssetsData/link.xml, Assets/AddressableAssetsData/link.xml.meta, Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, Assets/Prefabs/Enemies/bat_bullet.prefab, Assets/Prefabs/Player/Player.prefab, Assets/_Scenes/UI/SplashScreen.unity, Assets/_Scripts/Audio/FMOD/FMODAudioManager.cs, Assets/_Scripts/Enemies/BatBullet.cs, Assets/_Scripts/Managers/FeedbackAndDebugManager.cs, Assets/_Scripts/Managers/LevelDataManager.cs, Assets/_Scripts/Player/PlayerController.cs, Assets/_Sprites/Scenario/Tutorial/Ligth/LUZ01.png.meta
https://pinealpple-studios.atlassian.net/browse/TOF-381
- Bugs do play test
- Bloqueando teclasda ferramenta de debug.
- Realinhando o sentido do sprite do cuspe.
Full play test
N/A
=> [TOF-381]: Fix feedbacks

Assets/Animations/UI/ac_MainMenu.controller, Assets/Animations/UI/clip_backLanguage.anim, Assets/Animations/UI/clip_backLanguage.anim.meta, Assets/Animations/UI/clip_backSettings.anim, Assets/Animations/UI/clip_backVideo.anim, Assets/Animations/UI/clip_toAudio.anim, Assets/Animations/UI/clip_toControls.anim, Assets/Animations/UI/clip_toLanguage.anim, Assets/Animations/UI/clip_toLanguage.anim.meta, Assets/Animations/UI/clip_toSettings.anim, Assets/Animations/UI/clip_toVideo.anim, Assets/Ink/JSON/YXO-ENUS.json, Assets/Ink/JSON/YXO-ENUS.json.meta, Assets/Localization/Scripts/LocaleSelectorTest.cs, Assets/Localization/Tables/UI Text Shared Data.asset, Assets/Localization/Tables/UI Text_en.asset, Assets/Localization/Tables/UI Text_pt-BR.asset, Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, Assets/_Scenes/Playground/Localization_Test.unity, Assets/_Scenes/UI/MainMenu.unity, Assets/_Scripts/UI/MainMenuAnimationController.cs
https://pinealpple-studios.atlassian.net/browse/TOF-
Múltiplos idiomas para o TOF
Utilizando a ferramenta Localization, pude criar uma tabela com um identificador para cada linha e suas respectivas palavras em cada idioma. Em cada objeto com texto, atribuo esta chave ao componente Localize String Event.
Interagi com todas as telas de menu.
https://github.com/Pineapple-Studios/tears-of-fire/assets/110950216/9cbeda8d-35d8-48e5-bf7e-63ffe4d3401c
=> UI Localization

Assets/AddressableAssetsData/link.xml, Assets/AddressableAssetsData/link.xml.meta, Assets/Animations/Playground/clip_tear_one.anim, Assets/Animations/Playground/clip_tear_two.anim, Assets/Animations/Tutorial/GenericTutorial/clip_show_tutorial.anim, Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, Assets/Prefabs/Playground/Bossfight.prefab, Assets/_Scripts/Camera/CinemachineShakeManager.cs, Assets/_Scripts/Enemies/Pool.cs, Assets/_Scripts/Engines/PopUp_Tutorial.cs, Assets/_Scripts/Player/PlayerCombat.cs, Assets/_Scripts/Playground/PollingDrops.cs, Assets/_Scripts/Playground/TargetHandler.cs, Assets/_Scripts/Playground/TucanoRexProps.cs, Assets/_Scripts/Puzzles/Magnetic/Platform.cs, Assets/_Scripts/UI/Tutorial/TutorialCaller.cs, Assets/_Scripts/UI/Tutorial/TutorialController.cs, Assets/_Scripts/Utils/InstaKillElement.cs
https://pinealpple-studios.atlassian.net/browse/TOF-465
- [OK] Sumir tutorial após realizar a ação
- [OK] Fora da parede tear 3 / 4
- [OK] Colocar boss mais próximo das paredes
- [OK] Agua no chao dano
- [OK] Projeteis do boss reiniciar
- [OK] Camera shake respawn boss
- [OK] Camera oce
- [OK] Indulgencia no ataque
Correção dos bugs acima descritos
Full game play
N/A
=> [TOF-465]: Fix bugs

Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, Assets/_Scripts/Audio/FMOD/FMODAudioManager.cs, Assets/_Scripts/Enemies/BatWalkStart.cs, Assets/_Scripts/Enemies/Enemy.cs, Assets/_Scripts/Enemies/IWalkStart.cs, Assets/_Scripts/Enemies/Jumper.cs, Assets/_Scripts/Enemies/JumperWalkStart.cs, Assets/_Scripts/Enemies/SpiderWalkStart.cs, Assets/_Scripts/Enemies/WormWalkStart.cs, Assets/_Scripts/Engines/DoorLockedAnimationTrigger.cs, Assets/_Scripts/Items/LifeItem.cs, Assets/_Scripts/Player/PlayerCombat.cs, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/Playground/StartBoss.cs, Assets/_Scripts/Playground/StartBossGroupHandler.cs, Assets/_Scripts/Playground/TargetHandler.cs, Assets/_Scripts/Rumble/RumbleManager.cs, Assets/_Sprites/Player/svart-0.png.meta
https://pinealpple-studios.atlassian.net/browse/TOF-438
-
- Adição de hitfreeze 0 por 0.05s ao atacar o inimigo
- Sons de morte e ataque de alguns inimigos
Jogar o jogo de ponta a potna
N/A
=> TOF- 438: hit freeze ao atacar os inimigos

Assets/AddressableAssetsData/link.xml, Assets/AddressableAssetsData/link.xml.meta, Assets/Animations/Puzzles/MagneticB/ac_MagneticPlatformB.controller, Assets/Animations/Puzzles/MagneticB/clip_pathBack_02.anim, Assets/Animations/Puzzles/MagneticB/clip_pathBack_02.anim.meta, Assets/Animations/Puzzles/MagneticB/clip_transition_02.anim, Assets/Animations/Puzzles/MagneticB/clip_transition_02.anim.meta, Assets/Animations/Puzzles/MagneticC/ac_MagneticPlatformC.controller, Assets/Animations/Puzzles/MagneticC/clip_patchBack_03.anim, Assets/Animations/Puzzles/MagneticC/clip_patchBack_03.anim.meta, Assets/Animations/Puzzles/MagneticC/clip_transition_03.anim, Assets/Animations/Puzzles/MagneticC/clip_transition_03.anim.meta, Assets/_Scripts/Player/PlayerCombat.cs, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/Puzzles/Magnetic/MagneticHandler.cs, Assets/_Scripts/Puzzles/Magnetic/Platform.cs
NO TICKET
- Bugs do magnetísmo e slow motion
```
Eu como ...
Executei ...
E ...
Então ...
```
=> NO-TICKET: Solving soft locks

Assets/PostProcessing/Brightness/BrightnessManagerProfile.asset, Assets/PostProcessing/Tutorial_Profiles/TutorialProfile.asset, Assets/Prefabs/Player/Player.prefab, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/VFX/VFXPlayerLightByLife.cs, Assets/_Scripts/VFX/VFXPlayerLightByLife.cs.meta
https://pinealpple-studios.atlassian.net/browse/TOF-87
- Falta de luminescencia no jogo
- Adição de script de VFX no player para controlar esse parâmetros
Jogar o jogo todo, ganhando e perdendo vida
N/A
=> TOF-87: Light by life

Assets/Animations/Engines/StartGame/clip_transisiton.anim, Assets/PostProcessing/Brightness/BrightnessManagerProfile.asset, Assets/PostProcessing/Tutorial_Profiles/TutorialProfile.asset, Assets/Prefabs/Player/Player.prefab, Assets/_Scripts/Enemies/Pool.cs, Assets/_Scripts/GameEngines/AchievementHandler.cs, Assets/_Scripts/GameEngines/AchievementUISetup.cs, Assets/_Scripts/NPC/NPC.cs, Assets/_Scripts/Player/PlayerProps.cs, Assets/_Scripts/VFX/VFXPlayerLightByLife.cs, Assets/_Scripts/VFX/VFXPlayerLightByLife.cs.meta
- https://pinealpple-studios.atlassian.net/browse/TOF-549
- https://pinealpple-studios.atlassian.net/browse/TOF-557
- Knockback nas poças das goteiras
- Mais de um hit para morrer no lado do magnetísmo
- Reposicionamento da poça
- Remoção do knockback nas mesmas já que o hit freeze já resolve nesse ocasião
- Missão da história foi adicionada (Lembrar que temos 2 Yxos)
Morrer de diversas formas
N/A
=> TOF-549: Bug fixes & mission history

Assets/Animations/UI/clip_backVideo.anim, Assets/Animations/UI/clip_startGame.anim, Assets/Animations/UI/clip_toVideo.anim, Assets/Fonts/Ogenblik-v2.asset, Assets/Fonts/Ogenblik-v2.asset.meta, Assets/Fonts/Ogenblik.asset, Assets/Localization/Tables/UI Text Shared Data.asset, Assets/Localization/Tables/UI Text_en.asset, Assets/Localization/Tables/UI Text_pt-BR.asset, Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset, Assets/PostProcessing/Tutorial_Profiles/TutorialProfile.asset, Assets/_Scenes/UI/MainMenu.unity, Assets/_Scripts/Audio/BtnHoverSound.cs, Assets/_Scripts/Audio/FMOD/VolumeSlider.cs, Assets/_Scripts/UI/Quit.cs, Assets/_Scripts/UI/ResolutionController.cs
https://pinealpple-studios.atlassian.net/browse/TOF-556
https://pinealpple-studios.atlassian.net/browse/TOF-552
Não havia controle de brilho na tela de configurações de vídeo.
Dropdown não sabia qual resolução estava selecionada
Algumas navegações de botões não estavam fazendo sentido
Dropdown 100%
Slider para controlar o brilho da tela nas configurações de vídeo
Navegações de botão 100%
SFX na mudança de volume
Splash screen e todas as possibildades dos Menus Iniciais
N/A
=> [TOF-556] Feedback do professor quanto a UI
